import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#08110F',
  },
  scrollContent: {
    paddingTop: 16,
    paddingBottom: 110,
    paddingHorizontal: 16,
  },
  greetingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  greetingSub: {
    fontSize: 12,
    fontWeight: '700',
    color: '#74817B',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  greetingName: {
    fontSize: 30,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.8,
  },
  greetingAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#101917',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  balanceCard: {
    backgroundColor: '#101917',
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    position: 'relative',
    overflow: 'hidden',
  },
  mainBalanceWrapper: {
    alignItems: 'center',
    marginVertical: 4,
  },
  balanceLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#74817B',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 2,
  },
  balanceAmount: {
    fontSize: 34,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.8,
  },
  balanceDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.05)',
    marginVertical: 12,
  },
  statsGrid: {
    gap: 8,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  statBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#131D1A',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  statIconBg: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statContent: {
    flex: 1,
  },
  statLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#74817B',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 1,
  },
  statValue: {
    fontSize: 14.5,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.2,
  },
  pbHighlight: {
    paddingBottom: 28,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 96,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#10B981',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    zIndex: 40,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  fabDisabled: {
    backgroundColor: '#131D1A',
    shadowColor: 'transparent',
    opacity: 0.5,
  },
  skeletonOnDark: {
    marginTop: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  skeletonBalanceOnDark: {
    marginTop: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  sectionHeaderPadded: {
    paddingHorizontal: 4,
    marginBottom: 16,
  },
  filterContainer: {
    flexDirection: 'row',
    backgroundColor: '#101917',
    borderRadius: 14,
    padding: 4,
    marginBottom: 24,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.04)',
  },
  filterPill: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  filterPillActive: {
    backgroundColor: '#131D1A',
    borderColor: 'rgba(255,255,255,0.06)',
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#74817B',
  },
  filterLabelActive: {
    color: '#10B981',
  },
});
