// Colors matching the Stitch design
export const COLORS = {
  background: '#f8f9fa',
  surface: '#ffffff',
  primary: '#006948',
  primaryContainer: '#00855d',
  primaryFixed: '#85f8c4',
  onPrimaryFixedVariant: '#005137',
  secondary: '#4b41e1',
  secondaryFixed: '#e2dfff',
  tertiary: '#825100',
  tertiaryFixed: '#ffddb8',
  onSurface: '#191c1d',
  onSurfaceVariant: '#3d4a42',
  outline: '#6d7a72',
  outlineVariant: '#bccac0',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  surfaceContainer: '#edeeef',
  surfaceContainerLow: '#f3f4f5',
  surfaceContainerHigh: '#e7e8e9',
};

export const CATEGORY_ICONS: Record<
  string,
  { icon: string; lib: 'Ionicons' | 'MaterialIcons'; color: string; bg: string }
> = {
  All: { icon: 'apps', lib: 'Ionicons', color: COLORS.primary, bg: '#e8f0fe' },
  Food: { icon: 'restaurant', lib: 'MaterialIcons', color: '#e65100', bg: '#fff3e0' },
  Transport: { icon: 'directions-car', lib: 'MaterialIcons', color: '#1565c0', bg: '#e3f2fd' },
  Shopping: { icon: 'shopping-bag', lib: 'MaterialIcons', color: '#c62828', bg: '#fce4ec' },
  Entertainment: { icon: 'movie', lib: 'MaterialIcons', color: '#6a1b9a', bg: '#f3e5f5' },
  Bills: { icon: 'receipt-long', lib: 'MaterialIcons', color: '#2e7d32', bg: '#e8f5e9' },
  Travel: { icon: 'flight', lib: 'MaterialIcons', color: '#00695c', bg: '#e0f7fa' },
  Health: { icon: 'favorite', lib: 'MaterialIcons', color: '#b71c1c', bg: '#ffebee' },
  Other: { icon: 'more-horiz', lib: 'MaterialIcons', color: '#424242', bg: '#f5f5f5' },
};

// Premium high-quality avatars matching the design mockup
export const avatars = {
  womanWithGlasses:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDAU839kCrt_d__s6wCW1BquK-tXeEDRc3jq90beQIb8YuHwa1t8qJIdlW_nRP4xZXMAf-RPK1r1WCvIriCrYoh7gDBmXeWj6IsFkTnHti3XOIlkBdEiKGaAfj8xQmc9atuJWNEIpV3FZVipCO-n4n20v3ak-KwrRf3ZDuGqzOgvyt8Sipy2WVUuSPvpvu4N9t1z_sBaG3QGT9S81DmGdK9h4xZ6T_Zd6hoM_fT1PL7KGxhALDK9C_mgcJQcFBG3YCL_Kv1rQMNnAfX',
  fintechMan:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuD5T5AJUovvhA_WnRPgEHHUebHGXF5_1EiHG95y-QfKq2nOO07Mu6O3nzSp4AjHOG8hjAGd0Le9T3VMsQ554EcRvn-FBqlSpjy3oLYsJUgXfzsRNskrMk9B58aBpvnyrr9dunlwrQ3t-uLtHtQ5AeVKOCn-64fTFblLeVHlXrsHWRLrpvOIYhhnMeriv4c4aLSPUpLcih10KZ6yXzN32ixRZd3TUiAozHsESLzxhXawBgffwZTpUF4UXguT6m8ijF1N9kQL0fwVx9xM',
  groupLaugh:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuB8OeW6SCZ9iaJP1S0BtPntjELgjQnKPmd1O-E6ApVGkFBSRfT2d92dSkScE08EEYkyiNg2nhBsS2IOOKT0NJgw1hegtfA4t2Q8XwMB3DPUv_GAGQsJvQm6lufUWvyQw1kI4bGDmoB5euQuzSvWZ3fGs3UQUSp_K3Q444DPua5FMyn1SBLwrIxD9hLseaYWaXhvciDpZm-ZIR_ayJiH9x52PjjSUuqUCl3uVI86jlzRcXOc9rznXPr2mZP8vshtznTBIxjYq4mHlTZU',
  minimalistWoman:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuD6erY7eCAowHNemv8kHNZ_vU5EVoghv6bEahNN2ZFDlCYFIfvuePAZl5yb31uMy56UQCM6nBMW6_FOqk84q_Nv5fEp5UATPm-f8ejLczRho3hGQIMxIEWPHKKAaLNLsjrEZi4rK8JcgYdi27Xo_HiXNlD20AC-goE8m6y1gLPn_CEEhkuqCD-71w_y4XtHss8QtnMx6qMDwQqxrCwCLEQJAxOOIVeEZ3WYI10uWcE_ljnALx7a20kjycg31rpNk1PCVNK7kYVie-eX',
};

const SEEDS = [
  'Felix',
  'Aneka',
  'Jack',
  'Tigger',
  'Kiki',
  'Scooter',
  'Mimi',
  'Rocky',
  'Oliver',
  'Jasper',
  'Chloe',
  'Buddy',
  'Bella',
  'Daisy',
  'Zoe',
  'Max',
  'Lucy',
  'Charlie',
  'Milo',
  'Coco',
  'Bailey',
  'Buster',
  'Cody',
  'Cooper',
  'Duke',
  'Harley',
  'Lola',
  'Lucky',
  'Maggie',
  'Marley',
  'Molly',
  'Murphy',
  'Oscar',
  'Penny',
  'Princess',
  'Rex',
  'Rudy',
  'Sasha',
  'Shadow',
  'Sophie',
  'Samson',
  'Rusty',
  'Toby',
  'Tucker',
  'Winston',
  'Ziggy',
  'Bear',
  'Gizmo',
  'Sammy',
  'Teddy',
  'Abby',
  'Angel',
  'Annie',
  'Baby',
  'Bandit',
  'Beau',
  'Bo',
  'Callie',
  'Casper',
  'Chester',
  'Cleo',
  'Dixie',
  'Gigi',
  'Grace',
  'Jake',
  'Lady',
  'Lily',
  'Lulu',
  'Mac',
  'Madison',
  'Mickey',
  'Nala',
  'Otis',
  'Peanut',
  'Pepper',
  'Piper',
  'Riley',
  'Rocco',
  'Romeo',
  'Roscoe',
  'Ruby',
  'Sam',
  'Sandy',
  'Shelby',
  'Simba',
  'Stella',
  'Sugar',
  'Sydney',
  'Zeus',
  'Zoey',
  'Alfred',
  'Archie',
  'Aria',
  'Atlas',
  'Barnaby',
  'Beaufort',
  'Benedict',
  'Benjamin',
  'Caleb',
];
const BG_COLORS = [
  'b6e3f4',
  'ffdfbf',
  'c0aede',
  'd1d4f9',
  'ffd5dc',
  'c8edd8',
  'fce8b2',
  'd3e2fd',
  'f4dcd6',
  'f2ffc4',
  'f2d6ff',
  'd6ffe7',
  'ffe2d6',
  'e8ffd6',
  'ffd6f5',
  'd6fff5',
  'fff5d6',
  'd6e8ff',
  'ffd6d6',
  'e5ffd6',
];

export const PREDEFINED_AVATARS = Array.from({ length: 100 }, (_, i) => {
  const seed = SEEDS[i % SEEDS.length] + i;
  const bg = BG_COLORS[i % BG_COLORS.length];
  return `https://api.dicebear.com/7.x/avataaars/png?seed=${seed}&backgroundColor=${bg}`;
});

export const CURRENCY_SYMBOL = '₹';
