import { StyleSheet } from 'react-native';
import { COLORS } from '../../../constants/theme';

export const createGroupStyles = StyleSheet.create({
  // Modal container styles
  progressRow: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 24,
    marginBottom: 12,
  },
  progressDot: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.surfaceContainer,
  },
  progressDotActive: {
    backgroundColor: COLORS.secondary,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.errorContainer,
    marginHorizontal: 24,
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  errorText: {
    fontSize: 12,
    color: COLORS.error,
    fontWeight: '600',
  },

  // StepInfo styles
  stepContent: {
    paddingHorizontal: 24,
    paddingBottom: 20,
  },
  dropdownHeaderText: {
    fontSize: 15,
    fontWeight: '500',
    color: COLORS.onSurface,
  },
  dropdownItemLabel: {
    fontSize: 14,
    color: COLORS.onSurfaceVariant,
    fontWeight: '500',
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: 20,
    width: '100%',
    elevation: 4,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
  },
  primaryBtnDisabled: { opacity: 0.5, elevation: 0 },
  primaryBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },

  // StepMembers styles
  membersStep: { height: 500 },
  memberCountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 12,
  },
  memberCountLabel: {
    fontSize: 12,
    color: COLORS.outline,
    fontWeight: '600',
  },
  memberAvatarRow: { flexDirection: 'row' },
  memberAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.surface,
  },
  memberAvatarText: { fontSize: 10, fontWeight: '700', color: '#fff' },
  searchList: { flexGrow: 1, marginHorizontal: 0 },
  emptySearchText: {
    textAlign: 'center',
    color: COLORS.outline,
    fontSize: 13,
    paddingVertical: 16,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.surfaceContainerLow,
  },
  searchResultAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primaryFixed,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  searchResultAvatarText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.primary,
  },
  searchResultInfo: { flex: 1 },
  searchResultName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.onSurface,
  },
  searchResultEmail: { fontSize: 12, color: COLORS.outline },
  toggleBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: COLORS.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleBtnAdded: {
    backgroundColor: COLORS.secondary,
    borderColor: COLORS.secondary,
  },
  membersActions: {
    paddingHorizontal: 24,
    paddingTop: 12,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surfaceContainerLow,
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 48,
    borderWidth: 1,
    borderColor: COLORS.surfaceContainer,
    marginHorizontal: 24,
    marginBottom: 8,
  },
  inputIcon: { marginRight: 10 },
  textInput: {
    flex: 1,
    color: COLORS.onSurface,
    fontSize: 15,
    fontWeight: '500',
  },
  backBtn: { marginTop: 14, alignItems: 'center', paddingVertical: 4 },
  backBtnText: { fontSize: 13, color: COLORS.outline, fontWeight: '600' },

  // StepReview styles
  inputLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.outline,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
    marginLeft: 4,
  },
  reviewCard: {
    alignItems: 'center',
    backgroundColor: COLORS.primaryFixed,
    borderRadius: 20,
    padding: 24,
    marginBottom: 20,
  },
  reviewEmoji: { fontSize: 48, marginBottom: 12 },
  reviewName: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.onSurface,
    marginBottom: 4,
  },
  reviewDescription: {
    fontSize: 13,
    color: COLORS.outline,
    textAlign: 'center',
    marginBottom: 12,
  },
  reviewMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,0,0,0.05)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  reviewMetaText: { fontSize: 12, color: COLORS.outline, fontWeight: '600' },
  reviewMemberList: { marginBottom: 20 },
  reviewMemberItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.surfaceContainerLow,
    gap: 12,
  },
  reviewMemberAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.secondaryFixed,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewMemberAvatarText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.secondary,
  },
  reviewMemberName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.onSurface,
  },
  reviewMemberEmail: { fontSize: 12, color: COLORS.outline },
  helpText: {
    fontSize: 13,
    color: COLORS.outline,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 18,
    fontWeight: '500',
  },
});
